* TTX

  The successor to the TTB Teletekst browser which broke due to some changes in
  the Teletekst website. TTB was in Python, but TTX is written in C.  TTX is
  very young, but the basics work.

** providers

   TTB only supported the Dutch Teletekst system, but TTX aims to support other
   Teletekst providers as well. Currently supported:

   - Eins (German)
   - Eén Teletekst (Belgian, Dutch)
   - HRT (Croatian)
   - MTV3 (Finnish)
   - NOS Teletekst (Dutch)
   - ORF (Austrian)
   - RAI Televideo (Italian)
   - RTP (Portuguese)
   - RTVE (Spanish)
   - RTV (Slovenian)
   - YLE (Finnish)

   TTX is designed to make it easy to add other providers, esp. when they are
   mere variations of providers which are already supported. See
   =src/providers/=

** dependencies

   Just some very common libraries:

   - glib/gobject/gio
   - gtk+ 3.x
   - libsoup 2.4
   - libxml2

   (and for (re)building you'll the typically tools – gcc or clang and friends,
   autotools, libtool, pkg-config.

** download

   For tarballs, see:
   http://code.google.com/p/ttx-teletext/downloads/list
